/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#002022',
        'inverse-on-surface': '#2e3134',
        'surface-container-high': '#282a2e',
        'secondary-fixed-dim': '#ddb7ff',
        'on-error': '#690005',
        'primary-container': '#2d5bff',
        primary: '#b8c3ff',
        'on-primary-fixed-variant': '#0035bd',
        'surface-container': '#1d2023',
        'inverse-surface': '#e1e2e7',
        'tertiary-container': '#007980',
        'secondary-container': '#6f00be',
        'on-secondary': '#490080',
        'error-container': '#93000a',
        'surface-container-lowest': '#0c0e12',
        secondary: '#ddb7ff',
        'on-secondary-fixed': '#2c0051',
        'inverse-primary': '#104af0',
        'surface-container-low': '#191c1f',
        'secondary-fixed': '#f0dbff',
        'primary-fixed': '#dde1ff',
        background: '#111417',
        'on-error-container': '#ffdad6',
        'on-surface': '#e1e2e7',
        'on-primary-container': '#efefff',
        'surface-variant': '#323539',
        surface: '#111417',
        outline: '#8e90a2',
        tertiary: '#00dbe7',
        'outline-variant': '#434656',
        'surface-dim': '#111417',
        'on-tertiary-fixed-variant': '#004f54',
        error: '#ffb4ab',
        'tertiary-fixed-dim': '#00dbe7',
        'on-tertiary-container': '#c0faff',
        'surface-tint': '#b8c3ff',
        'on-secondary-fixed-variant': '#6900b3',
        'surface-bright': '#37393d',
        'primary-fixed-dim': '#b8c3ff',
        'surface-container-highest': '#323539',
        'on-background': '#e1e2e7',
        'on-primary-fixed': '#001355',
        'on-tertiary': '#00363a',
        'on-primary': '#002387',
        'tertiary-fixed': '#74f5ff',
        'on-surface-variant': '#c4c5d9',
        'on-secondary-container': '#d6a9ff',
        success: '#3ddc97',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'card-padding': '24px',
        'section-gap': '32px',
        'gutter-stack': '16px',
        'margin-page': '20px',
        'element-gap': '8px',
      },
      fontFamily: {
        'label-md': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Sora', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Sora', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'display-lg': ['Sora', 'sans-serif'],
        'headline-lg-mobile': ['Sora', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      keyframes: {
        float: {
          '0%,100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-14px)' },
        },
        breathe: {
          '0%,100%': { opacity: '0.45', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.18)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        riseIn: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scan: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(400%)' },
        },
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        breathe: 'breathe 3s ease-in-out infinite',
        shimmer: 'shimmer 3s linear infinite',
        riseIn: 'riseIn .45s cubic-bezier(.2,.8,.2,1) both',
        scan: 'scan 3.5s linear infinite',
      },
    },
  },
  plugins: [],
}
